name: Release Extension

on:
  push:
    branches:
      - main

jobs:
  # CodeQL analysis job
  codeql-analysis:
    name: "CodeQL Analysis"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]  # Removed PowerShell, kept JavaScript

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  # Release job that publishes the extension
  release:
    runs-on: ubuntu-latest
    needs: codeql-analysis  # Ensures CodeQL analysis completes first

    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment to run tfx-cli
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install tfx-cli
      - name: Install tfx-cli
        run: npm install -g tfx-cli

      # Run the tfx extension publish command
      - name: Publish Extension to Visual Studio Marketplace
        run: |
          cd src
          tfx extension publish --publisher mightoraio --manifest-globs vss-extension.json --token ${{ secrets.VS_MARKETPLACE_TOKEN }} --rev-version